AxonIQ/reference-guide

part-iii-infrastructure-components/repository-and-event-store.md
Resolves https://github.com/AxonFramework/ReferenceGuide/issues/101
=> Added upcaster example for Jackson serialized event.

1.1-concepts/architecture-overview.md, 1.3-infrastructure-components/command-dispatching.md
=> New module split documentation.

1.1-concepts/messaging-concepts.md
=> Note about UOW result.

1.3-infrastructure-components/command-dispatching.md, 1.3-infrastructure-components/event-processing.md, 1.4-advanced-tuning/performance-tuning.md
=> Builder pattern impact

1.1-concepts/configuration-api.md, 1.2-domain-logic/event-handling.md, 1.2-domain-logic/sagas.md, 1.3-infrastructure-components/event-processing.md, 1.3-infrastructure-components/spring-boot-autoconfiguration.md
Addresses `EventProcessingConfiguration` changes in regard to the 4.0 AxonFramework version.
Relates to https://github.com/AxonFramework/ReferenceGuide/issues/51
=> Event processing configuration

introduction/architecture-overview/architecture-overview.md, introduction/architecture-overview/ddd-cqrs-concepts.md, introduction/architecture-overview/event-driven-microservices.md
Typos and one suggested change to Event Sourcing description
=> Improvements

configuring-infrastructure-components/event-processing/event-processors.md
This PR will update the documentation about configuration of Saga's Event Processing
=> Update description of how to configure Saga Event Processing

SUMMARY.md, operations-guide/setting-up-axon-server/heartbeat-monitoring.md
Explain how to activate high-level heartbeat monitoring in order to detect disconnection between client and server as soon as possible.
=> Heartbeat Monitoring Documentation

extensions/kafka.md
This pull request updates the entire `kafka.md` file to accommodate for all the recent changes which have been made in the [Kafka Extension](https://github.com/AxonFramework/extension-kafka).
As such it resolves issue #105
=> [#105]  Align Kafka Extension page

implementing-domain-logic/command-handling/external-command-handler.md
In external-command-handler change typo pleased to placed
=> Fix typo pleased -> placed in external-command-handler.md

SUMMARY.md, implementing-domain-logic/command-handling/aggregate-polymorphism.md
Explains Aggregate Polymorphism.
=> Aggregate Polymorphism.

introduction/release-notes/bug-fixes.md, introduction/release-notes/release-notes.md
This pull request provides the release notes for 4.3.
Additionally, it adds the bug fixes for 4.2.1, 4.2.2 and 4.3.
=> 4.3 Release Notes

implementing-domain-logic/command-handling/aggregate.md
This PR introduces the "Aggregate Command Handler Creation Policy" section to the `aggregate.md` page. It shortly explains the new `@CreationPolicy` / `AggregateCreationPolicy` set up through which you can define a command handling method to:
- `ALWAYS` create an aggregate when handling the command,
- `NEVER` create an aggregate when handling the command, or
- `CREATE_IF_MISSING`
This pull request relates to framework issue [#667](https://github.com/AxonFramework/AxonFramework/issues/667)
=> Aggregate Command Handler Creation Policy

axon-server/installation/axon-server-clustering.md
=> Corrected default port from 8223 to 8224

axon-server/migration/README.md, axon-server/migration/non-axon-server-to-axon-server.md, axon-server/migration/standard-to-enterprise-edition.md
Added a new section for Migration (Axon SE to Axon EE and non-Axon Servers to Axon Server)
Each sub-section contains
Pre-Upgrade
Upgrade
Verification and
Notes
=> New Migration Section

SUMMARY.md, axon-server/administration/monitoring/README.md, axon-server/administration/monitoring/grpc-metrics.md
- Added a sub-section _gRPC metrics_ to the revamped monitoring section
=> Monitoring changes - Added grpc metrics

SUMMARY.md, release-notes/README.md, release-notes/axon-framework-extensions.md, release-notes/rn-axon-framework/README.md, release-notes/rn-axon-framework/rn-af-major-releases.md, release-notes/rn-axon-framework/rn-af-minor-releases.md, release-notes/rn-axon-server/README.md, release-notes/rn-axon-server/rn-as-major-releases.md, release-notes/rn-axon-server/rn-as-minor-releases.md
Revamped Release notes section
- Split by Axon Framework and Axon Server
- Each section is further split into sub-sections (Major Releases / Minor Releases)
- Included all versions till date
=> Revamped Release Notes Section

axon-server/administration/backup-and-messaging-only-nodes.md
Literature to explain this and close out #141
=> Messaging Nodes - Explanation of "min-active-backups"

.gitbook.yaml, axon-framework/queries/README.md, extensions/tracing.md
Redirect changes and some minor link corrections
=> Global Redirect changes

SUMMARY.md, axon-server/administration/admin-configuration/cluster-template.md
Simple semantic changes to the Cluster Template page.
=> Semantic Changes to Cluster Template page

SUMMARY.md, extensions/kotlin.md
This PR will resolve #161 
Added Kotlin extension description and mini examples.
=> Add Kotlin extension

SUMMARY.md, axon-server/administration/error-codes.md
New section for Error Codes under Axon Server - Administration
=> New section for Error Codes

axon-framework/deadlines/deadline-managers.md, axon-framework/events/event-processors.md, axon-framework/events/event-versioning.md, axon-framework/messaging-concepts/message-intercepting.md, axon-framework/messaging-concepts/supported-parameters-annotated-handlers.md, axon-framework/tuning/event-snapshots.md
Close #181, #182 , #184 , #185 , #186 , #187 , #191
=> features-and-enhancements-4.5

axon-framework/messaging-concepts/message-intercepting.md
Close #195 
Removed Note about Javax and Jakarta, since we decided to stay with Javax only.
=> Remove Note about Javax and Jakarta

axon-framework/modules.md
As "requested" by @smcvb here https://github.com/AxonFramework/axon-bom/pull/8 :-)
=> Add simplified Gradle BOM import description

axon-server/administration/admin-configuration/configuration.md
Update property name for logging filename.
=> Fix missing <tr>. Update property name for logging filename.

axon-framework/messaging-concepts/message-intercepting.md
This pull request adjusts the description to be more to the point.
On top of that, it expands the code samples to show more permutations of exception handlers.
=> Expand upon the exception handler section

axon-framework/queries/query-dispatchers.md, axon-server/performance/flow-control.md
Documented usage of streaming query
=> Streaming query documentation

axon-server/installation/docker-k8s/axon-server-ee.md, axon-server/installation/docker-k8s/axon-server-se.md
=> The Docker and Kubernetes installation pages were in need of an update

axon-server/installation/docker-k8s/axon-server-se.md
was not working (missing space)
=> fix h2 for axon server

SUMMARY.md, axon-server/administration/admin-configuration/README.md, axon-server/administration/admin-configuration/grpc-api.md
=> GRPC Event processor administration API documentation 

axon-server/administration/admin-configuration/grpc-api.md
Solves https://github.com/AxonIQ/axon-server/issues/1060
=> Documentation for GRPC API for cluster configuration.

axon-framework/queries/query-dispatchers.md, axon-server/performance/flow-control.md
=> Streaming query alignments

extensions/kafka.md
This is a fix for https://github.com/AxonIQ/reference-guide/issues/274
=> update the Kafka extension docs. Mostly to accommodate for the `StreamableKafkaMessageSource` changes.

axon-framework/events/event-processors/streaming.md
Axon 4.6.0 will introduce saving the `resetContext` into the `ReplayToken` for access during the replay. This PR documents the usage of this feature.
=> Document how to use and access the ReplayToken.replayContext

axon-framework/modules.md
Add the Jakarta modules to the list, with a short explanation above.
=> Add Jakarta modules

axon-framework/upgrading-to-4-7.md
Add a Migration Automation section, explaining the new OpenRewrite recipes and how to use them.
=> Add a Migration Automation section

SUMMARY.md, axon-framework/deadlines/deadline-managers.md, axon-framework/modules.md, extensions/jobrunrpro.md, release-notes/rn-extensions/rn-jobrunrpro/README.md, release-notes/rn-extensions/rn-jobrunrpro/rn-jobrunrpro-major-releases.md
Fixes https://github.com/AxonIQ/reference-guide/issues/310
=> Add information about the JobRunr Pro extension.

axon-framework/upgrading-to-4-7.md
The tab next to "persistence.xml" has a "untitled" title.
=> Minor fix for the title of the tab.

axon-framework/deadlines/deadline-managers.md, axon-framework/deadlines/event-schedulers.md, axon-framework/events/event-processors/README.md, axon-framework/events/event-processors/streaming.md, axon-framework/messaging-concepts/message-intercepting.md, axon-framework/tuning/event-snapshots.md
From looking through the closed issues under 4.8.0 it seems the most important bits are covered.
=> Several updates in preparation for the 4.8.0 release.

extensions/spring-aot.md
Fixes https://github.com/AxonIQ/reference-guide/issues/326
=> Add the Spring Ahead of Time extension.

axon-framework/messaging-concepts/supported-parameters-annotated-handlers.md
Covers https://github.com/AxonIQ/reference-guide/issues/329
=> Reformat supported parameters documentation to show a table

axon-server/installation/docker-k8s/README.md
update docker image documentation and add information about the change of the latest image from 4.6.11 to 2023.2.0.
=> Update Axon Server docker information

axon-framework/deadlines/deadline-managers.md
=> Deprecated method in DbSchedulerDeadlineManager bean definition

axon-server/installation/docker-k8s/README.md
readme links are case sensitive
=> Fixed docker-k8s reference links
