1.2-domain-logic/command-model.md
1.2-domain-logic/event-handling.md
1.2-domain-logic/query-handling.md
1.2-domain-logic/sagas.md
1.3-infrastructure-components/event-processing.md
1.4-advanced-tuning/advanced-customizations.md
1.4-advanced-tuning/metrics-and-monitoring.md
book.json

We are using `codetabs` plugin to render our tabs in the guide now.
You should be able to serve gitbook guide locally on http://localhost:4000: `$ gitbook serve`
Gitbook local installation: https://toolchain.gitbook.com/setup.html

Switching to 'codetabs' gitbook plugin

---

1.2-domain-logic/command-model.md
1.2-domain-logic/event-handling.md
1.2-domain-logic/query-handling.md
1.2-domain-logic/sagas.md
1.3-infrastructure-components/event-processing.md
1.4-advanced-tuning/advanced-customizations.md
1.4-advanced-tuning/metrics-and-monitoring.md
book.json

Reverts AxonIQ/reference-guide#39
The `codetabs` syntax we introduces is not inline with the latest of Gitbook.
We have to use this syntax (as we did before):
```
{% tabs %} {% tab title="First Tab" %} My first tab content {% endtab %}
{% tab title="Second Tab" %} My second tab content {% endtab %} {% endtabs %}
```
`gitbook cli` cant be used locally ...
Please revert

Revert "Switching to 'codetabs' gitbook plugin"

---

configuring-infrastructure-components/event-processing/event-processors.md
implementing-domain-logic/event-handling/dispatching-events.md
implementing-domain-logic/event-handling/handling-events.md
implementing-domain-logic/query-handling/handling-queries.md

This PR introduce adjustments to the documentation in regards to new features which have been introduced in Axon Framework 4.1.
The following features now have been documented:
- [Allow TrackingEventProcessor segments to be split and merged](https://github.com/AxonFramework/AxonFramework/pull/969)
- [Introduce an EventGateway to simplify Event Message publication](https://github.com/AxonFramework/AxonFramework/issues/954)
- [Add a "registerEventHandler" shorthand to Configuration](https://github.com/AxonFramework/AxonFramework/issues/887)
- [The QueryBus should be able to cope with primitives](https://github.com/AxonFramework/AxonFramework/issues/650)

Guide adjustments in regards to new features introduces in Axon Framework 4.1

---

extensions/spring-cloud.md

When working with Spring Cloud Kubernetes I tried to setup the SpringCloudHttpBackupCommandRouter only to find the example code omitted the Registration object required by parent SpringCloudCommandRouter.  I figured I would do a PR to correct it.

Added localServiceInstance of type Registration to backup command router code example

---

configuring-infrastructure-components/deadlines.md

Recently I had a use-case that relied on time in the event message. When attempting to test I ran into an issue with being able to inject java clocks. I was able to find out that there is a global clock that can be used but it wasn't easy to find.
I made a suggestion to add it to the docs on Stack Overflow and was asked to raise a PR.
This conversation can be followed here: 
https://stackoverflow.com/questions/60026771/how-can-i-test-an-aggregate-that-relies-on-time/60026833#60026833
Feel free to suggest better locations in the docs. I didn't want it to be too disruptive to what already exists.

Added Info about global clock to docs

---

axon-framework/events/event-serialization.md

Slightly rephrased the explanation of content type converters. It is no longer required for Upcasters to be aware of the possible content type converters. This is hidden from the users and automatically "figured out" by the framework.

Improved the explanation of content type converters

---

axon-server-introduction.md

I really hope it is not a messing platform, since the platform is intended to clean up the mess :-)

fix: typo in Axon Server Flow Control description

---

extensions/tracing.md

This PR updates 4.4 reference guide with new configuration possibility for Tracing Extension introduced with https://github.com/AxonFramework/extension-tracing/pull/78 and https://github.com/AxonFramework/extension-tracing/pull/55

update extension tracing guide

---

axon-framework/axon-framework-commands/command-handlers.md

Regarding commit bc329d3:
It's either "... the Aggregate structure grow_s_ beyond ..." or "... the Aggregate structure_s_ grow beyond ...", but two times s is one to much. I have chosen this correction since it is one Aggregate and its one internal structure.

Corrrected typos in Command Handler description

---

axon-framework/axon-framework-commands/modeling/aggregate-polymorphism.md

The unnecessary line breaks in the middle of the sentences are irritating and disturb the flow while reading.

docs: removed unnessesary line breaks

---

extensions/spring-cloud.md
release-notes/axon-framework-extensions.md

Update the Spring Cloud page to better reflect the current status of the [Spring Cloud Extension](https://github.com/AxonFramework/extension-springcloud).
Most noteworthy in this are the removal (deprecation in code) of the [`SpringCloudHttpBackUpCommandRouter`](https://github.com/AxonFramework/extension-springcloud/blob/master/springcloud/src/main/java/org/axonframework/extensions/springcloud/commandhandling/SpringCloudHttpBackupCommandRouter.java) and the introduction of the [`CapabilityDiscoveryMode`](https://github.com/AxonFramework/extension-springcloud/blob/master/springcloud/src/main/java/org/axonframework/extensions/springcloud/commandhandling/mode/CapabilityDiscoveryMode.java) in its stead.
Whilst touching this file, I aimed to update its contents entirely, as it was by no means …

Adjust the Spring Cloud page

---

axon-framework/modules.md

This pull request enhances the Modules page by including a section about the [Axon Bill of Materials](https://github.com/AxonFramework/axon-bom).
In doing so, it explains the purpose of the BOM, where it can be found and how it can be used.
At the top of the page, the reader is directed towards the existence of the BOM as the recommended approach.
Lastly, the `Note` has been replaced by a descriptive title, as that is in line with the (desired) approach in the rest of the Reference Guide.

Add a section about the Bill of Materials

---

axon-framework/axon-framework-commands/command-handlers.md
axon-framework/axon-framework-commands/infrastructure.md
extensions/jgroups.md
extensions/spring-cloud.md

The `CommandBus` infrastructure page has been given a thorough adjustment in this pull request.
The main driver for starting this is issue #188, which points out that the `RoutingStrategy` currently does not have a dedicated section wherein it is described.
To accompany a good spot for the `RoutingStrategy` within the infrastructure page, several portions have been moved around and added.
These can be summarized as follows:
- Renamed sections, to construct three main sections, for the `CommandGateway` (unchanged), a local `CommandBus` and a distributed `CommandBus`
- Changed the introduction sections of the main page, the local and distributed `CommandBus` sections
- Removed the mention of the `AxonServerCommandBus` in the local section
- Add a "Local Segment" section to the "Distributed …

[#188] Command Bus Infrastructure adjustments 

---

axon-framework/events/event-versioning.md

This pull request introduces a section that describes how to configure upcasters.
In total, it shows how to use the `Configurer`, `@Order` annotation, and `EventUpcasterChain` approaches.
In doing so, this pull request resolves issue #97

[#97] Add Upcaster Configuration section

---

axon-framework/events/event-serialization.md

This pull request introduces a `Default Typing` section to the serializers page.
It explains the benefit it gives and how it can be configured.
This pull request resolves #172

[#172] Add information about defaultTyping to the Serializer 

---

axon-framework/events/event-handlers.md
axon-framework/messaging-concepts/supported-parameters-annotated-handlers.md

The supported resolvable parameters page wasn't very consistent.
It didn't contain all the options provided, nor the specifics on Event Handler parameters.
That's fixed in this pull request, which moves the set of parameters from the `event-handlers.md` file to the `supported-parameters-annotated-handlers.md` file.
On top of that, all grammar is validated, samples have been extended and minor additions for clarity have been done.
As this PR adds the `@SourceId` resolvable parameter too, this ticket resolves issue #152

[#152] Update Supported Parameters Page

---

getting-started/quick-start.md

Parts 4 and 5 of the tutorial videos are linked to specific timestamps. This change removes the timestamps to have the videos start from the beginning

Remove timestamps from tutorial videos

---

axon-server/administration/backups.md

Closes #232 
There is one sentence that I'd like to improve on but not sure about a good word for it: 
`These are files with name larger than the last name returned in the filenames from the backup endpoint.`
I'd like to replace the word "last" with something else. Because once put before name -> `last name` it can be confused with  "achternaam." Any suggestions @smcvb or @domaincomponents?

Typo & minor adjustments in Backups section of AS docs

---

axon-framework/events/event-bus-and-event-store.md

There's too much ambiguity within the Distributing Events section. 
It should differentiate how to deal with event distribution within a bounded context and between bounded contexts.

Fine-tune Distributing Events section

---

extensions/kafka.md

Additional docs for https://github.com/AxonFramework/extension-kafka/pull/195

docs: described the upcaster support in extension-kafka

---

axon-framework/queries/query-dispatchers.md

... to match the usage in the method
The description code could never compile, and was misleading when first read (till we worked out it was a typo)
(It would be nice to have the example extracted from working code with a GitHub repo to back it)

Fixed the event parameter name in the EventHandler example

---

axon-framework/events/event-versioning.md

This pull request adds a caveat that the context-aware upcasters context depends on the size of the event stream the upcaster acts on.

Add caveat for the context-aware upcaster

---

axon-framework/events/event-processors/streaming.md
axon-server/administration/event-processors.md
axon-server/administration/reset-event-processor-token.md

Documentation on how to reset event processor tokens using AF, AS Rest API or AS Connector.
See also the [PR](https://github.com/AxonIQ/code-samples/pull/193) in the samples repo.

Added docs for token reset

---

axon-server/administration/admin-configuration/configuration.md

Added descriptions (partly from release notes) for the following configuration properties:
```
axoniq.axonserver.web-socket-allowed-origins
axoniq.axonserver.command-queue-capacity-per-client
axoniq.axonserver.query-queue-capacity-per-client
axoniq.axonserver.enterprise.license-directory
axoniq.axonserver.event.use-mmap-index
axoniq.axonserver.replication.use-mmap-index
axoniq.axonserver.snapshot.use-mmap-index
axoniq.axonserver.event.force-clean-mmap-index
axoniq.axonserver.replication.force-clean-mmap-index
axoniq.axonserver.snapshot.force-clean-mmap-index
axoniq.axonserver.event.aggregate.prefetch
axoniq.axonserver.event.aggregate.retry.attempts
axoniq.axonserver.event.aggregate.retry.delay
axoniq.axonserver.event.new-index-suffix
axoniq.axonserver.event.global-index-suffix …
```

Added description of several configuration options

---

axon-server/administration/admin-configuration/command-line-interface.md

Added Description of  command line arguments valid for all commands, namely `-S`, `-s`, `-i`, `-o`.
This includes details on how to set up using SSL/TLS.
In the table describing Commands, the header "Command option" was changed to "Command name", since "options" is already used to mean something else in the existing syntax description.

Added description of command line arguments valid for all commands

---

axon-framework/events/event-processors/README.md

Added deadletter queue, see https://github.com/AxonFramework/AxonFramework/issues/2021

Deadletter documentation added

---

axon-framework/tuning/event-snapshots.md

Add a description about the `RevisionSnapshotFilter` to the Filtering Snapshot Events section. 
This will further clarify that users only have to add the `@Revision` annotation to configure snapshot filtering in most snapshotting scenarios.

Append `RevisionSnapshotFilter` description to Filtering Snapshot Events sub-section

---

axon-framework/events/event-processors/README.md

Add a notice stating why the `SequencedDeadLetterQueue` does not work for sagas for the time being.

Add notices on Dead-Letter Queue support for Sagas

---

axon-framework/events/event-processors/streaming.md

This pull request introduces a dedicated "Token Stealing" section onto to the Streaming Processor page. 
The intent is to guide users further in what token stealing is, why it happens, when it happens, and what the consequence may be to them.
In doing so, this pull request resolves #288.

[#288] Add Token Stealing subsection to Tracking Tokens

---

axon-framework/events/event-processors/README.md
axon-framework/events/event-processors/streaming.md
axon-framework/events/event-processors/subscribing.md

This pull request replaces `@Autowired` configuration samples for `ConfigurerModule` bean examples.
This is required as a follow up from the Spring version change accompanied with 4.6 of Framework.
These changes cause `@Autowired` methods using Axon Framework configuration beans to cause circular dependency issues _or_ they're invoked out of order.
To resolve this, users can provide a `ConfigurerModule` bean instead, as Axon Framework will capture these and invoke them as part of initiating the lifecycle of the Axon Framework application.

Replace @Autowired configuration samples for ConfigurerModule

---

README.md
SUMMARY.md
axon-framework/introduction.md
axon-framework/upgrading-to-4-7.md

Since it is extremely unusual for Axon Framework to introduce breaking changes in a minor release, this pull request adds a dedicated section under the Axon Framework documentation to help users in their upgrade. 
This page explains several scenarios a user may be in, providing a plan of attack to upgrade to 4.7.
Next to this, I've added a notice on the front page of the Reference Guide and on the base Axon Framework page to point out that 4.7 contains breaking changes.

Add an Upgrading to Axon Framework 4.7 section

---

axon-server/administration/admin-configuration/command-line-interface.md

The unregister node should only be used to remove a node from a cluster and not for any upgrading features etc. Clarifying in the guide to reflect the same

Enhance the unregister node cli command description

---

axon-framework/events/event-versioning.md

Fixed the equals check in canUpcast examples.
The previous equals check can fail if the `SerializedType` from the `IntermediateEventRepresentation` is not a `SimpleSerializedType`.

Fixed the equals check in canUpcast examples

---

axon-server/administration/backups.md

Specifies that the context parameter refers to the replication group and adds an example including `_admin` .

Added note about replication groups to backup log segments from
